---
- hosts: all
  gather_facts: false
  vars:
    remote_unprivileged_user: tmp_ansible_test_user
  tasks:
  
  - name: fetch a docker container to use for a demo
    delegate_to: localhost
    docker_container:
      name: docker_ansible_nonroot_test
      image: centos:centos7

  - name: add new docker container to the inventory for later connecting
    add_host:
      name: docker_ansible_nonroot_test

  - name: collect facts on the new docker image
    delegate_to: docker_ansible_nonroot_test
    setup:

  - name: note the home directory for the Ansible user
    set_fact: 
      remote_user_home: "{{ ansible_env.HOME }}"

  - name: add an unprivileged user to the docker image
    delegate_to: docker_ansible_nonroot_test
    become: true
    user:
      name: '{{ remote_unprivileged_user }}'
    register: user

  - name: create an `.ssh` directory for holding `authorized_keys`
    delegate_to: docker_ansible_nonroot_test
    become: true
    file:
      path: "{{ user.home }}/.ssh"
      owner: '{{ remote_unprivileged_user }}'
      state: directory
      mode: 0700

  - name: duplicate authorized_keys
    delegate_to: docker_ansible_nonroot_test
    become: true
    copy:
      src: '{{ remote_user_home }}/.ssh/authorized_keys'
      dest: '{{ user.home }}/.ssh/authorized_keys'
      owner: '{{ remote_unprivileged_user }}'
      mode: 0600
      remote_src: yes

  - name: who am i when connecting as the unprivileged user?
    delegate_to: docker_ansible_nonroot_test
    remote_user: '{{ remote_unprivileged_user }}'
    command: whoami
    register: whoami_result

  - debug: var=whoami_result

  # TODO: Clean up after myself